"""Initial migration.

Revision ID: 310ceef3f375
Revises: 7dd841bdda61
Create Date: 2023-03-23 08:22:41.655404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '310ceef3f375'
down_revision = '7dd841bdda61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('mobileNumber',
               existing_type=sa.VARCHAR(length=25),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('mobileNumber',
               existing_type=sa.VARCHAR(length=25),
               nullable=False)

    # ### end Alembic commands ###
